apiVersion: v1
kind: Service
metadata:
  name: maintenance-pod-service-service
spec:
  type: NodePort # Use NodePort or LoadBalancer for external access
  ports:
  - port: 445
    targetPort: 445
  - port: 139
    targetPort: 139
  selector:
    app: maintenance-pod-service