apiVersion: apps/v1
kind: Deployment
metadata:
  name: maintenance-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maintenance-pod
  template:
    metadata:
      labels:
        app: maintenance-pod
    spec:
      containers:
      - name: smb
        image: ghcr.io/magicalfruit/maintenance-pod:main
        imagePullPolicy: Always
        volumeMounts:
        - name: sonarr
          mountPath: /mnt/longhorn/sonarr
        ports:
        - containerPort: 445
        - containerPort: 139
      volumes:
#      - name: sonarr
#        nfs:
#          server: sonarr-pv-claim.longhorn-system.svc.cluster.local
#          path: /export/sonarr-pv-claim
      - name: sonarr
        persistentVolumeClaim:
          claimName: sonarr-pv-claim